# Generated by Django 4.1.4 on 2023-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AccountApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgers",
            name="balance",
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name="ledgers",
            name="description",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
