# Generated by Django 4.1.5 on 2023-01-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AccountApp", "0002_alter_ledgers_balance_alter_ledgers_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("debit", models.IntegerField()),
                ("credit", models.IntegerField()),
                ("balance", models.IntegerField(default=False)),
                ("description", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppProfile",
            fields=[
                ("name", models.CharField(max_length=150)),
                (
                    "ledger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="AccountApp.appledger",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(old_name="Ledgers", new_name="Ledger",),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("rate", models.IntegerField()),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AccountApp.ledger",
                    ),
                ),
            ],
        ),
    ]
