# Generated by Django 4.1.5 on 2023-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0004_alter_appledger_balance_alter_appledger_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='debit',
            field=models.IntegerField(default=0),
        ),
    ]
