# Generated by Django 4.1.5 on 2023-01-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0005_alter_ledger_credit_alter_ledger_debit'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLedger1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('balance', models.IntegerField(default=False, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('user', models.CharField(max_length=100)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='AccountApp.ledger')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='userLedger2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('balance', models.IntegerField(default=False, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('user', models.CharField(max_length=100)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='AccountApp.ledger')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='userLedger3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('balance', models.IntegerField(default=False, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('user', models.CharField(max_length=100)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='AccountApp.ledger')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='appprofile',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='AppLedger',
        ),
        migrations.DeleteModel(
            name='AppProfile',
        ),
    ]
