# Generated by Django 4.1.5 on 2023-01-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0006_userledger1_userledger2_userledger3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userledger1',
            name='user',
            field=models.CharField(default='Not Defined', max_length=100),
        ),
        migrations.AlterField(
            model_name='userledger2',
            name='user',
            field=models.CharField(default='Not Defined', max_length=100),
        ),
        migrations.AlterField(
            model_name='userledger3',
            name='user',
            field=models.CharField(default='Not Defined', max_length=100),
        ),
    ]
