# Generated by Django 4.1.5 on 2023-02-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0009_alter_userledger1_user_alter_userledger2_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
