# Generated by Django 4.1.5 on 2023-02-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0010_alter_userprofile_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userledger1',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userledger2',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userledger3',
            options={'ordering': ['id']},
        ),
    ]
