# Generated by Django 4.1.5 on 2023-02-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0012_alter_ledger_credit_alter_ledger_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userledger1',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='AccountApp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userledger2',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='AccountApp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userledger3',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='AccountApp.userprofile'),
        ),
    ]
